// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATUSPACKETV1_H_
#define FLATBUFFERS_GENERATED_STATUSPACKETV1_H_

#include "flatbuffers/flatbuffers.h"

struct StatusPacketV1;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) StatusPacketV1 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t pulse_timestamp_;

 public:
  StatusPacketV1()
      : pulse_timestamp_(0) {
  }
  StatusPacketV1(uint64_t _pulse_timestamp)
      : pulse_timestamp_(flatbuffers::EndianScalar(_pulse_timestamp)) {
  }
  uint64_t pulse_timestamp() const {
    return flatbuffers::EndianScalar(pulse_timestamp_);
  }
};
FLATBUFFERS_STRUCT_END(StatusPacketV1, 8);

#endif  // FLATBUFFERS_GENERATED_STATUSPACKETV1_H_
